language: node_js
node_js:
- '7'
- '6'
notifications:
  email:
    on_success: change
    on_failure: always
cache:
  directories:
  - node_modules
before_install:
- npm install -g npm@4
after_script:
- npm run coverage
- cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
- "./node_modules/.bin/codeclimate-test-reporter < ./coverage/lcov.info"
env:
  global:
  - secure: KKnkaJ/GvIDy3DGj7aiJsxmzcXia28+AYK2D3dgNojaULlDILcD9s8RtivKWbCDCYkp+tOB5KgbLkQQcM+G2/XMOCRDT2fE47MR2mmugREtXpRcEojZ49nb+is+M5LGYpyA5e8fJJvVUESESO2fZV8PVM3EOJTLoD4BUxmd6MpfAvrLKWah7A5XD/RyfzOI+X17PC7rMMrUmYpOJAWC2GGxVakfmJzTJoMEZhvBO98kWvKV0qGQoogK14sX/8cNkRvDdtZ4ZuJxxEEpNFTxEEgE02lRvCiz2/a7zEI0Z69LlYP3+ESDHshcVGGm/5v2wWOvv01qS9l3LEwrc6AioULZfMa6wablUwypdl5NlYyKUtNUj0OZ4R4hyG/VIK4z6Kd0xaCmEwU+knnYTiIP0H5ioefLrm15x4uWk6cjLst8W1ADvu/ZOkFXT4dfb25ywBlCPgQqOArRc3IV7ZKPSekYNpXI+5mj1nh5/2oOkoKxngRjxrmYxlD4xPezzwEd7eor4huttSK5kBL/92GmESFdBrRM+IBuK+BZwTMmLPvxBrwRALhUn1awOU2zstxdOESDiDnICD2/rHSaXG9jIcoypMDnThrpK0XPI5xI1FQGg+OIhfDoduU8eXunpAciVSEtInx93StGnuBfhkNXJYFDdANior/QrRog44WAGjxk=
  - secure: P3ccU889avcj3hNvWi80PFyd91OgcecJsq2evAu8lOiZagzbTeDSe1E/WjHpWt5nqs0dLyPTgpclye+vHok4w+Nih9mLFA5jlPsB1EaCB9OjCwPqQCCF67VfL9rn5OoHAbiYIBlMRt1z8S7Ov/8PgcEs/8ZVGbIAKMmmvAqfgGZhHuvaDyW8dy49dOsTUyb3E41W6LJ94gQrfXxAaKkrpOTHuC+XdiUxXgDkVxITc72GsISRtL/415DbSk394XPc8Wn1ewt0WxlwwhOUoJJ9tyu0jNtn1iE6aqGcPDNQy/9R8pruPoBNz3i8Txhq39ss+26M9gvyI/Z7L2Rl4QL5ccJZIdGiywhGgO6sQ37hf5LcTOf2Fcs/E8DvhhwR+XcMSTHPU3CbV8P+xoJairJww5vroE5u1ohk6oPhLWJM3JOwIjRjpA4RVQSoNHtjXK6XZJReD0x5CkS24F+D4Nohvb5DEzKnkOiC+QruPWEK1kfkOl5qPuI+M1VMGk/BerEPSHnNFTY4DMMzF04+B5WFlwE9sidSxZZhG257Gi6R55uWv05Sca4v9XX3+9fZDGYiJI888QOb4wiHmS8w2e7SY3E30fjCYDUJ2N2AJcWpgKEb3e0Vr59FlzeE+PBCnX5YJh37ybK5UtNvqhKcEDDCwoPiNQtyHBYvPv5PC/HICbk=
  - secure: qnvd0j3OM1mDeoIgtGPkQ0zqctEu1EMFjtSWd9Vf5ZbKtvOzbGV6Q0tCvJ6/CTd7K1DBwbpdtaSGL0nwDri8IkM0ZuH4xLd0pd2Y1rZbZePVaE4e3FfQfdvFg78Y5vZ84byh9E8wS3iIQ0byuMY+vJyMXGEWXpGrKqHWXAq/xsolhGH3NixKLJYThiqpVGiNn1xIDFC4tOi36I76JjIhci3s7RtniwMLBzIzZ1/unX19KTelgtd46eEeKbK2OE02sZ0sfJKWw7QbqbcxFJQk8HGabZmE9A2focb9wQui0IkKXKfwZYUOof69IzDrJhebkOjk06dc6BvF72FBjkKFZ0mQQiXY6q2GgPUxDeLKVZ08Ycze6k2GGUVMjUUV46slxdzHKWsSVI4AooE6cUHlg+DwWc7BH7LP0Yj0QSNaP8Co9Fa4vYPDDgfYcgDyvDLeP2J0EpkliNFLjgk9GFNtSpQxf/4rchos5Fh/vEAp2+gj6ctCNJaAtIjioLJUTGNHuWVcReO/JBhAIKeAFMmmEuHynE767qxGO4iJQ5wyKYGaut9PTXR2FaX8jGKpMm/ht3fBYWWTZdcvRUJ53P7ACJJHwsYpnz9zoF9Kj+KrMD4iAV2VzH9N+ala1A8AurUE0oqk3+2SxPNHp1SRSGHnIIB3UVXuQWBTbxJHcbhArBo=
